-- Schema PostgreSQL para Age Run
CREATE TABLE IF NOT EXISTS usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  senha TEXT NOT NULL,
  sexo TEXT DEFAULT 'masculino',
  altura DOUBLE PRECISION NULL,
  data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  codigo_recuperacao TEXT NULL,
  codigo_expiracao TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS pesagens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  peso DOUBLE PRECISION NOT NULL,
  gordura_percentual DOUBLE PRECISION NULL,
  massa_muscular_percentual DOUBLE PRECISION NULL,
  agua_percentual DOUBLE PRECISION NULL,
  massa_ossea DOUBLE PRECISION NULL,
  metabolismo_basal INTEGER NULL,
  idade_metabolica INTEGER NULL,
  gordura_visceral INTEGER NULL,
  data_pesagem TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  excluido INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_pesagens_usuario_id ON pesagens(usuario_id);
CREATE INDEX IF NOT EXISTS idx_pesagens_data ON pesagens(data_pesagem);
CREATE INDEX IF NOT EXISTS idx_pesagens_excluido ON pesagens(excluido);
