-- Schema PostgreSQL para Age Run
CREATE TABLE IF NOT EXISTS usuarios (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  senha TEXT NOT NULL,
  sexo TEXT DEFAULT 'masculino',
  altura DOUBLE PRECISION NULL,
  data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  codigo_recuperacao TEXT NULL,
  codigo_expiracao TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS pesagens (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  peso DOUBLE PRECISION NOT NULL,
  gordura_percentual DOUBLE PRECISION NULL,
  massa_muscular_percentual DOUBLE PRECISION NULL,
  agua_percentual DOUBLE PRECISION NULL,
  massa_ossea DOUBLE PRECISION NULL,
  metabolismo_basal INTEGER NULL,
  idade_metabolica INTEGER NULL,
  gordura_visceral INTEGER NULL,
  data_pesagem TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  excluido INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS rp_testes_historico (
  id BIGSERIAL PRIMARY KEY,
  usuario_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  treinador_id INTEGER NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  prova VARCHAR(20) NULL,
  tempo_segundos INTEGER NOT NULL,
  distancia_km DOUBLE PRECISION NOT NULL,
  pace_segundos_km DOUBLE PRECISION NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_pesagens_usuario_id ON pesagens(usuario_id);
CREATE INDEX IF NOT EXISTS idx_pesagens_data ON pesagens(data_pesagem);
CREATE INDEX IF NOT EXISTS idx_pesagens_excluido ON pesagens(excluido);
CREATE INDEX IF NOT EXISTS idx_rp_testes_usuario_data ON rp_testes_historico(usuario_id, criado_em);
