<?php

declare(strict_types=1);

require_once __DIR__ . '/../src/config.php';
require_once __DIR__ . '/../src/db.php';

header('Content-Type: application/json; charset=utf-8');

function out(array $payload, int $status = 200): never
{
    http_response_code($status);
    echo json_encode($payload, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    exit;
}

function requestPath(): string
{
    return parse_url($_SERVER['REQUEST_URI'] ?? '/', PHP_URL_PATH) ?? '/';
}

function isDevContext(): bool
{
    $cfg = appConfig();
    $basePath = (string) ($cfg['app_base_path'] ?? '/controle');
    $uriPath = requestPath();

    return $basePath === '/dev' || str_starts_with($uriPath, '/dev/');
}

function dbColumnExistsSeed(string $table, string $column): bool
{
    $driver = strtolower((string) (appConfig()['db']['driver'] ?? 'mysql'));

    if ($driver === 'sqlite') {
        $rows = dbFetchAll("PRAGMA table_info({$table})");
        foreach ($rows as $row) {
            if (($row['name'] ?? '') === $column) {
                return true;
            }
        }
        return false;
    }

    if ($driver === 'pgsql' || $driver === 'postgres' || $driver === 'postgresql') {
        $row = dbFetchOne(
            'SELECT 1 FROM information_schema.columns WHERE table_name = :table AND column_name = :column LIMIT 1',
            [':table' => $table, ':column' => $column]
        );
        return $row !== null;
    }

    $rows = dbFetchAll("SHOW COLUMNS FROM {$table} LIKE :column", [':column' => $column]);
    return count($rows) > 0;
}

function ensureCoreSeedTables(): void
{
    $driver = strtolower((string) (appConfig()['db']['driver'] ?? 'mysql'));

    if ($driver === 'sqlite') {
        dbExecute(
            'CREATE TABLE IF NOT EXISTS usuarios (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                nome TEXT NOT NULL,
                email TEXT NOT NULL UNIQUE,
                senha TEXT NOT NULL,
                sexo TEXT DEFAULT "masculino",
                altura REAL NULL,
                data_cadastro DATETIME DEFAULT CURRENT_TIMESTAMP,
                codigo_recuperacao TEXT NULL,
                codigo_expiracao DATETIME NULL
            )'
        );
        dbExecute(
            'CREATE TABLE IF NOT EXISTS pesagens (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                usuario_id INTEGER NOT NULL,
                peso REAL NOT NULL,
                gordura_percentual REAL NULL,
                massa_muscular_percentual REAL NULL,
                agua_percentual REAL NULL,
                massa_ossea REAL NULL,
                metabolismo_basal INTEGER NULL,
                idade_metabolica INTEGER NULL,
                gordura_visceral INTEGER NULL,
                data_pesagem DATETIME DEFAULT CURRENT_TIMESTAMP,
                excluido INTEGER DEFAULT 0
            )'
        );
        dbExecute(
            'CREATE TABLE IF NOT EXISTS rp_testes_historico (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                usuario_id INTEGER NOT NULL,
                treinador_id INTEGER NOT NULL,
                prova TEXT NULL,
                tempo_segundos INTEGER NOT NULL,
                distancia_km REAL NOT NULL,
                pace_segundos_km REAL NOT NULL,
                criado_em DATETIME DEFAULT CURRENT_TIMESTAMP
            )'
        );
        return;
    }

    if ($driver === 'pgsql' || $driver === 'postgres' || $driver === 'postgresql') {
        dbExecute(
            'CREATE TABLE IF NOT EXISTS usuarios (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome TEXT NOT NULL,
                email TEXT NOT NULL UNIQUE,
                senha TEXT NOT NULL,
                sexo TEXT DEFAULT \'masculino\',
                altura DOUBLE PRECISION NULL,
                data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                codigo_recuperacao TEXT NULL,
                codigo_expiracao TIMESTAMP NULL
            )'
        );
        dbExecute(
            'CREATE TABLE IF NOT EXISTS pesagens (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                usuario_id INTEGER NOT NULL,
                peso DOUBLE PRECISION NOT NULL,
                gordura_percentual DOUBLE PRECISION NULL,
                massa_muscular_percentual DOUBLE PRECISION NULL,
                agua_percentual DOUBLE PRECISION NULL,
                massa_ossea DOUBLE PRECISION NULL,
                metabolismo_basal INTEGER NULL,
                idade_metabolica INTEGER NULL,
                gordura_visceral INTEGER NULL,
                data_pesagem TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                excluido INTEGER DEFAULT 0
            )'
        );
        dbExecute(
            'CREATE TABLE IF NOT EXISTS rp_testes_historico (
                id BIGSERIAL PRIMARY KEY,
                usuario_id INTEGER NOT NULL,
                treinador_id INTEGER NOT NULL,
                prova VARCHAR(20) NULL,
                tempo_segundos INTEGER NOT NULL,
                distancia_km DOUBLE PRECISION NOT NULL,
                pace_segundos_km DOUBLE PRECISION NOT NULL,
                criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )'
        );
        return;
    }

    dbExecute(
        'CREATE TABLE IF NOT EXISTS usuarios (
            id INT AUTO_INCREMENT PRIMARY KEY,
            nome VARCHAR(255) NOT NULL,
            email VARCHAR(255) NOT NULL UNIQUE,
            senha VARCHAR(255) NOT NULL,
            sexo VARCHAR(20) DEFAULT \'masculino\',
            altura DECIMAL(4,2) NULL,
            data_cadastro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            codigo_recuperacao VARCHAR(20) NULL,
            codigo_expiracao DATETIME NULL
        )'
    );
    dbExecute(
        'CREATE TABLE IF NOT EXISTS pesagens (
            id INT AUTO_INCREMENT PRIMARY KEY,
            usuario_id INT NOT NULL,
            peso DECIMAL(6,2) NOT NULL,
            gordura_percentual DECIMAL(5,2) NULL,
            massa_muscular_percentual DECIMAL(5,2) NULL,
            agua_percentual DECIMAL(5,2) NULL,
            massa_ossea DECIMAL(5,2) NULL,
            metabolismo_basal INT NULL,
            idade_metabolica INT NULL,
            gordura_visceral INT NULL,
            data_pesagem DATETIME DEFAULT CURRENT_TIMESTAMP,
            excluido TINYINT(1) DEFAULT 0
        )'
    );
    dbExecute(
        'CREATE TABLE IF NOT EXISTS rp_testes_historico (
            id INT AUTO_INCREMENT PRIMARY KEY,
            usuario_id INT NOT NULL,
            treinador_id INT NOT NULL,
            prova VARCHAR(20) NULL,
            tempo_segundos INT NOT NULL,
            distancia_km DECIMAL(10,4) NOT NULL,
            pace_segundos_km DECIMAL(10,4) NOT NULL,
            criado_em DATETIME DEFAULT CURRENT_TIMESTAMP
        )'
    );
}

if (!isDevContext()) {
    out(['error' => 'Seed permitido apenas no contexto /dev'], 403);
}

$confirm = strtolower(trim((string) ($_GET['confirm'] ?? '')));
if ($confirm !== 'simular') {
    out([
        'ok' => false,
        'message' => 'Para executar, acesse com ?confirm=simular',
        'example' => '/dev/seed-staging.php?confirm=simular',
    ], 400);
}

try {
    ensureCoreSeedTables();

    $athletes = [
        ['nome' => 'Moises Dev', 'email' => 'moises@staging.local', 'sexo' => 'masculino'],
        ['nome' => 'Carlos Sprint', 'email' => 'carlos@staging.local', 'sexo' => 'masculino'],
        ['nome' => 'Bruno Pace', 'email' => 'bruno@staging.local', 'sexo' => 'masculino'],
        ['nome' => 'Diego Longo', 'email' => 'diego@staging.local', 'sexo' => 'masculino'],
        ['nome' => 'Felipe Sub40', 'email' => 'felipe@staging.local', 'sexo' => 'masculino'],
        ['nome' => 'Ana Ritmo', 'email' => 'ana@staging.local', 'sexo' => 'feminino'],
        ['nome' => 'Julia Progresso', 'email' => 'julia@staging.local', 'sexo' => 'feminino'],
        ['nome' => 'Marina Forca', 'email' => 'marina@staging.local', 'sexo' => 'feminino'],
    ];

    $trainer = ['nome' => 'Treinador Dev', 'email' => 'treinador@staging.local', 'sexo' => 'masculino'];

    dbExecute("DELETE FROM pesagens WHERE usuario_id IN (SELECT id FROM usuarios WHERE email LIKE '%@staging.local')");
    dbExecute("DELETE FROM rp_testes_historico WHERE usuario_id IN (SELECT id FROM usuarios WHERE email LIKE '%@staging.local') OR treinador_id IN (SELECT id FROM usuarios WHERE email LIKE '%@staging.local')");
    dbExecute("DELETE FROM usuarios WHERE email LIKE '%@staging.local'");

    $passwordHash = password_hash('123456', PASSWORD_DEFAULT);

    dbExecute(
        'INSERT INTO usuarios (nome, email, senha, sexo) VALUES (:nome, :email, :senha, :sexo)',
        [
            ':nome' => $trainer['nome'],
            ':email' => $trainer['email'],
            ':senha' => $passwordHash,
            ':sexo' => $trainer['sexo'],
        ]
    );
    $trainerRow = dbFetchOne('SELECT id FROM usuarios WHERE email = :email LIMIT 1', [':email' => $trainer['email']]);
    $trainerId = (int) ($trainerRow['id'] ?? 0);

    $users = [];
    foreach ($athletes as $index => $athlete) {
        dbExecute(
            'INSERT INTO usuarios (nome, email, senha, sexo) VALUES (:nome, :email, :senha, :sexo)',
            [
                ':nome' => $athlete['nome'],
                ':email' => $athlete['email'],
                ':senha' => $passwordHash,
                ':sexo' => $athlete['sexo'],
            ]
        );

        $row = dbFetchOne('SELECT id FROM usuarios WHERE email = :email LIMIT 1', [':email' => $athlete['email']]);
        $userId = (int) ($row['id'] ?? 0);
        if ($userId <= 0) {
            continue;
        }

        $users[] = ['id' => $userId, 'nome' => $athlete['nome'], 'email' => $athlete['email'], 'sexo' => $athlete['sexo']];

        $pesoInicial = 102 - ($index * 3.1);
        $pesoAtual = $pesoInicial - (2.5 + ($index * 0.8));

        dbExecute(
            'INSERT INTO pesagens (usuario_id, peso, data_pesagem, excluido) VALUES (:uid, :peso, :data, 0)',
            [
                ':uid' => $userId,
                ':peso' => round($pesoInicial, 2),
                ':data' => date('Y-m-d H:i:s', strtotime('-21 days')),
            ]
        );

        dbExecute(
            'INSERT INTO pesagens (usuario_id, peso, data_pesagem, excluido) VALUES (:uid, :peso, :data, 0)',
            [
                ':uid' => $userId,
                ':peso' => round(($pesoInicial + $pesoAtual) / 2, 2),
                ':data' => date('Y-m-d H:i:s', strtotime('-10 days')),
            ]
        );

        dbExecute(
            'INSERT INTO pesagens (usuario_id, peso, data_pesagem, excluido) VALUES (:uid, :peso, :data, 0)',
            [
                ':uid' => $userId,
                ':peso' => round($pesoAtual, 2),
                ':data' => date('Y-m-d H:i:s', strtotime('-1 days')),
            ]
        );

        if ($trainerId > 0) {
            $tempo5k = 1800 - ($index * 35);
            $dist5k = 5.0;
            $pace5k = $tempo5k / $dist5k;

            dbExecute(
                'INSERT INTO rp_testes_historico (usuario_id, treinador_id, prova, tempo_segundos, distancia_km, pace_segundos_km, criado_em)
                 VALUES (:uid, :tid, :prova, :tempo, :dist, :pace, :data)',
                [
                    ':uid' => $userId,
                    ':tid' => $trainerId,
                    ':prova' => 'rp_5k',
                    ':tempo' => $tempo5k,
                    ':dist' => $dist5k,
                    ':pace' => $pace5k,
                    ':data' => date('Y-m-d H:i:s', strtotime('-2 days')),
                ]
            );
        }
    }

    if ($trainerId > 0 && dbColumnExistsSeed('usuarios', 'perfil')) {
        dbExecute("UPDATE usuarios SET perfil = 'treinador' WHERE id = :id", [':id' => $trainerId]);
    }

    if (dbColumnExistsSeed('usuarios', 'rp_5k')) {
        foreach ($users as $index => $u) {
            $rp5k = 1800 - ($index * 35);
            dbExecute('UPDATE usuarios SET rp_5k = :rp WHERE id = :id', [':rp' => $rp5k, ':id' => $u['id']]);

            if (dbColumnExistsSeed('usuarios', 'rp_5k_status')) {
                dbExecute("UPDATE usuarios SET rp_5k_status = 'aprovado' WHERE id = :id", [':id' => $u['id']]);
            }
        }
    }

    out([
        'ok' => true,
        'message' => 'Dados ficticios de staging criados com sucesso.',
        'login_padrao' => [
            'senha' => '123456',
            'exemplos' => [
                'moises@staging.local',
                'ana@staging.local',
                'treinador@staging.local',
            ],
        ],
        'usuarios_criados' => count($users) + 1,
    ]);
} catch (Throwable $e) {
    out(['ok' => false, 'error' => $e->getMessage()], 500);
}
